### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/kms-samples#5]
Could you add brief instructions on how to build the executable? If you are security-aware, you don't download and run executables... :)

Using Golang, it is probably not much to do.

**Comment by data-henrik** [comment]
Downloading just the source file and either running directly `go run encrypt.go` or first building (`go build encrypt.go`), then executing it (`./encrypt') works.

**Comment by cloudpitchford** [comment]
Please confirm the changes, @data-henrik, (thanks for your help!), and close when the changes have been validated.
